exclude_paths:
    - "AUTHORS.md"
    - "README.md"
    - "CONTRIBUTING.md"
    - "src/malign/__init__.py"
    - "src/malign/__main__.py"
    - "examples/*.py"
    - "tests/*.py"
    - "resources/bdpa/README.md"
    - "resources/cmudict/README.md"
    - "resources/neurodecipher/README.md"
    - "resources/northeuralex/README.md"
