language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update

install:
  - "python setup.py install"
  - "pip install codecov"

script:
  - "coverage run tests/test_malign.py"
  - "coverage run -a tests/test_matrix.py"
  - "coverage run -a tests/test_demo.py"

after_success:
  - "codecov"
